CREATE TABLE test(
    [Id] [bigint] IDENTITY(1,1) NOT NULL,
    [Text] [nvarchar](255) NOT NULL,
    CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED
        (
        [Id] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
)